fix(version): update version

diff --git a/.github/workflows/version.yaml b/.github/workflows/version.yaml
--- a/.github/workflows/version.yaml
+++ b/.github/workflows/version.yaml
@@ -1,17 +1,86 @@
 name: Semantic Versioning
 
 on:
-  pull_request:
+  push:
     branches:
       - '**'
       - '!main'
       - '!master'
-      - '!develop'
+  # pull_request:
+  #   branches:
+  #     - '**'
+  #     - '!main'
+  #     - '!master'
+  # types:
+  #   - labeled
+  #   - unlabeled
 
 jobs:
+  # version_check:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check Labels
+  #       if: |
+  #         !contains(github.event.pull_request.labels.*.name, 'release:patch') &&
+  #         !contains(github.event.pull_request.labels.*.name, 'release:minor') &&
+  #         !contains(github.event.pull_request.labels.*.name, 'release:major')
+  #       run: |
+  #         echo "::error::No labels found labels: `release:patch`, `release:minor`, `release:major`"
+  #         exit 1
+
+  # version_diff:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     chagned: ${{ steps.version_diff.outputs.changed }}
+  #   steps:
+  #     - name: Fetch Target Branch
+  #       run: |
+  #         git fetch origin ${{ github.base_ref }} --depth=1
+
+  #     - name: Save Version
+  #       id: version_diff
+  #       run: |
+  #         echo "changed=$(git diff origin/${{ github.base_ref }} HEAD --relative "./package.json" | grep "^+.\+version" | wc -l)" >> $GITHUB_OUTPUT
+
+  # version_update:
+  #   runs-on: ubuntu-latest
+  #   needs: [version_diff]
+  #   if: needs.version_diff.outputs.chagned == '0'
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.ref }}
+
+  #     - name: Git Config
+  #       if: steps.diff.outputs.changed == '0'
+  #       run: |
+  #         git config --global user.name 'github-actions[bot]'
+  #         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+  #         git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Update Version(Patch)
+  #       if: contains(github.event.pull_request.labels.*.name, 'release:patch')
+  #       run: pnpm version --patch --no-git-tag-version
+
+  #     - name: Update Version(Minor)
+  #       if: contains(github.event.pull_request.labels.*.name, 'release:minor')
+  #       run: pnpm version --minor --no-git-tag-version
+
+  #     - name: Update Version(Major)
+  #       if: contains(github.event.pull_request.labels.*.name, 'release:major')
+  #       run: pnpm version --major --no-git-tag-version
+
+  #     - name: Push Changes
+  #       run: |
+  #         git add .
+  #         git commit -m "v$(grep version package.json | awk -F \" '{print $4}')"
+  #         git push origin HEAD
+
   version:
-    # バージョンチェックはPRのみで実行
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -19,26 +88,24 @@ jobs:
           ref: master
 
       - name: Get New Version
-        id: curent_version
-        uses: martinbeentjes/npm-get-version-action@v1.3.1
-        with:
-          path: .
+        id: current_version
+        run: |
+          echo "version=$(cat package.json | jq -r '.version')""
 
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Get New Version
-        id: new_version
-        uses: martinbeentjes/npm-get-version-action@v1.3.1
-        with:
-          path: .
+        id: release_version
+        run: |
+          echo "version=$(cat package.json | jq -r '.version')""
 
       - name: Check version update
         id: check-version-update
         uses: ./.github/workflows/composite/check-version-update
         with:
-          current_version: ${{ steps.current_version.outputs.current-version }}
-          new_version: ${{ steps.new_version.outputs.current-version }}
+          current_version: ${{ steps.current_version.outputs.version }}
+          release_version: ${{ steps.release_version.outputs.version }}
 
       - name: Set Label to Pull Request
         if: github.event_name == 'pull_request'
